In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [7]:
df = pd.read_excel(r'/content/Folds5x2_pp.xlsx')
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [9]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 10)

In [12]:
#Building ANN#
ann = tf.keras.models.Sequential()

In [13]:
#adding layers#
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))#dense layer will create the layers bw input and hidden layers and units is num of layers#

In [14]:
#adding another hidden layer#
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))

In [15]:
#output layer#
ann.add(tf.keras.layers.Dense(units = 1,activation='sigmoid'))

In [16]:
#compile the model for applying propogation in the model#
ann.compile(optimizer='adam',loss = 'mean_squared_error')#optimizer reduces the loss#

In [18]:
#training our model#
ann.fit(x_train,y_train,batch_size=32,epochs=100)#The number of epochs is a hyperparameter that defines the number times that the learning algorithm will work through the entire training dataset. One epoch means that each sample in the training dataset has had an opportunity to update the internal model parameters. An epoch is comprised of one or more batchesand it also reduce the loss error#

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5469
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5469
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5625
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5156
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5625
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5625
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5625
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5469
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5312
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5938
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 205729.5312
Epoch 12/100
240/240 [===================

In [21]:
#predictions#
y_pred = ann.predict(x_test)

In [22]:
np.printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[  1.   456.57]
 [  1.   438.7 ]
 [  1.   436.09]
 ...
 [  1.   431.27]
 [  1.   441.17]
 [  1.   461.08]]
